#!/bin/bash

echo "🔑 EMERGENCY API KEY ROTATION SCRIPT"
echo "====================================="
echo ""
echo "⚠️  WARNING: Complete these steps IMMEDIATELY!"
echo ""
echo "1️⃣  OPENAI API KEY"
echo "   → Go to: https://platform.openai.com/api-keys"
echo "   → Delete your old key"
echo "   → Create new key"
echo "   → Run: fly secrets set OPENAI_API_KEY='new_key_here' --app bbr-production"
echo ""
echo "2️⃣  RESEND API KEY"
echo "   → Go to: https://resend.com/api-keys"
echo "   → Delete your old key" 
echo "   → Create new key"
echo "   → Run: fly secrets set RESEND_API_KEY='new_key_here' --app bbr-production"
echo ""
echo "3️⃣  UPSTASH REDIS"
echo "   → Go to: https://console.upstash.com/"
echo "   → Regenerate credentials for your database"
echo "   → Run: fly secrets set UPSTASH_REDIS_REST_URL='new_url' --app bbr-production"
echo "   → Run: fly secrets set UPSTASH_REDIS_REST_TOKEN='new_token' --app bbr-production"
echo ""
echo "4️⃣  FORM PASSWORD"
echo "   → Generate a new secure password"
echo "   → Run: fly secrets set FORM_PASSWORD='new_password' --app bbr-production"
echo ""
echo "5️⃣  VERIFY SECRETS"
echo "   → Run: fly secrets list --app bbr-production"
echo ""
echo "🛡️  After rotating all keys, your security incident will be FULLY resolved!"
