name: Link Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  link-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Run link checker
        run: npm run test:links
